Repository SWM-15th-ForU/freebe-Backend, pull requests merged in 2024-10, with the labels that each got.

#47 [FU-267] 신청서 리스트 필터링 API 구현
  .gitignore
  src/main/java/com/foru/freebe/errors/errorcode/ProductErrorCode.java
  src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
  src/main/java/com/foru/freebe/product/dto/photographer/ProductTitleDto.java
  src/main/java/com/foru/freebe/product/respository/ProductRepository.java
  src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
  src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
Labels: 🌟 feature

#50 [FU-270] 베타버전 출시 전 비즈니스 로직 개선
  .github/workflows/cd_workflow_dev.yml
  src/main/java/com/foru/freebe/auth/service/KakaoLoginService.java
  src/main/java/com/foru/freebe/config/SecurityConfig.java
  src/main/java/com/foru/freebe/errors/errorcode/AwsErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/MemberErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/ProductErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/ProductImageErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/ProfileErrorCode.java
  src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
  src/main/java/com/foru/freebe/product/dto/customer/ProductDetailResponse.java
  src/main/java/com/foru/freebe/product/dto/customer/ProductListResponse.java
  src/main/java/com/foru/freebe/product/dto/photographer/ProductRegisterRequest.java
  src/main/java/com/foru/freebe/product/dto/photographer/RegisteredProductResponse.java
  src/main/java/com/foru/freebe/product/dto/photographer/UpdateProductDetailRequest.java
  src/main/java/com/foru/freebe/product/entity/Product.java
  src/main/java/com/foru/freebe/product/entity/ProductImage.java
  src/main/java/com/foru/freebe/product/service/CustomerProductService.java
  src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
  src/main/java/com/foru/freebe/product/service/ProductDetailConvertor.java
  src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
  src/main/java/com/foru/freebe/profile/Controller/PhotographerProfileController.java
  src/main/java/com/foru/freebe/profile/dto/UpdateProfileRequest.java
  src/main/java/com/foru/freebe/profile/entity/ProfileImage.java
  src/main/java/com/foru/freebe/profile/service/CustomerProfileService.java
  src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
  src/main/java/com/foru/freebe/profile/service/ProfileService.java
  src/main/java/com/foru/freebe/reservation/dto/BasicReservationInfoResponse.java
  src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
  src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
  src/main/java/com/foru/freebe/reservation/dto/ReservationInfoResponse.java
  src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerPastReservationService.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
  src/main/java/com/foru/freebe/reservation/service/ReservationVerifier.java
  src/main/java/com/foru/freebe/s3/S3ImageService.java
  src/main/java/com/foru/freebe/s3/S3ImageType.java
  src/main/resources/application.yaml
  src/test/java/com/foru/freebe/member/service/PhotographerJoinServiceTest.java
  src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java
Labels: 🌟 feature, 🛠️ bugfix, ✨api-update, 🫧 refactoring

#53 [FU-274] 외부링크 업데이트 로직 추가 구현
  src/main/java/com/foru/freebe/auth/service/KakaoLoginService.java
  src/main/java/com/foru/freebe/errors/errorcode/LinkErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/ProductErrorCode.java
  src/main/java/com/foru/freebe/profile/entity/Link.java
  src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
Labels: 🛠️ bugfix

#49 [FU-268] 촬영일자에 대한 업데이트 API 구현
  src/main/java/com/foru/freebe/errors/errorcode/ReservationErrorCode.java
  src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
  src/main/java/com/foru/freebe/reservation/dto/FormComponent.java
  src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
  src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
  src/main/java/com/foru/freebe/reservation/dto/PastReservationFormComponent.java
  src/main/java/com/foru/freebe/reservation/dto/ReservationInfoResponse.java
  src/main/java/com/foru/freebe/reservation/dto/ReservationStatusUpdateRequest.java
  src/main/java/com/foru/freebe/reservation/dto/ShootingDate.java
  src/main/java/com/foru/freebe/reservation/dto/TimeSlot.java
  src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
  src/main/java/com/foru/freebe/reservation/service/ReservationService.java
  src/main/java/com/foru/freebe/reservation/service/ReservationVerifier.java
  src/test/java/com/foru/freebe/reservation/service/ReservationServiceTest.java
Labels: 🌟 feature

#51 [FU-249] Kakao OAuth 연결 끊기(회원 탈퇴) API 구현
  src/main/java/com/foru/freebe/auth/controller/AuthController.java
  src/main/java/com/foru/freebe/auth/dto/UnlinkRequest.java
  src/main/java/com/foru/freebe/auth/service/KakaoUnlinkService.java
  src/main/java/com/foru/freebe/errors/errorcode/AuthErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/MemberErrorCode.java
  src/main/java/com/foru/freebe/member/entity/DeletedMember.java
  src/main/java/com/foru/freebe/member/entity/Member.java
  src/main/java/com/foru/freebe/member/entity/Role.java
  src/main/java/com/foru/freebe/member/repository/DeletedMemberRepository.java
  src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
  src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
  src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
Labels: 🌟 feature

#55 [FU-295] 신청서 등록 API 에러 픽스
  src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
  src/main/java/com/foru/freebe/product/respository/ProductImageRepository.java
  src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
  src/main/java/com/foru/freebe/profile/Controller/PhotographerProfileController.java
  src/main/java/com/foru/freebe/profile/dto/CustomerViewProfileResponse.java
  src/main/java/com/foru/freebe/profile/dto/PhotographerViewProfileResponse.java
  src/main/java/com/foru/freebe/profile/service/CustomerProfileService.java
  src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
  src/main/java/com/foru/freebe/profile/service/ProfileService.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/test/java/com/foru/freebe/member/MemberRepositoryTest.java
  src/test/java/com/foru/freebe/member/service/PhotographerJoinServiceTest.java
  src/test/java/com/foru/freebe/product/service/PhotographerProductServiceTest.java
  src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java
  src/test/java/com/foru/freebe/reservation/service/ReservationServiceTest.java
Labels: 🛠️ bugfix

#57 [FU-299] 촬영 확정일자 업데이트 API 에러 픽스
  src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
  src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
  src/main/java/com/foru/freebe/reservation/dto/ShootingDateRequest.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
Labels: 🛠️ bugfix

#67 [FU-309] (bug fix) dev server env setting
  .github/workflows/cd_workflow_dev.yml
  .github/workflows/cd_workflow_prod.yml
Labels: 🛠️ bugfix

#68 [v1.0.0] 서비스 출시
  appspec.yml
Labels: 🧸 release

#70 [FU-307] 카카오 연결 끊기 API 버그 픽스
  src/main/java/com/foru/freebe/auth/service/KakaoUnlinkService.java
  src/main/java/com/foru/freebe/errors/errorcode/AuthErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/ProductErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/ProfileErrorCode.java
  src/main/java/com/foru/freebe/member/entity/Member.java
Labels: 🛠️ bugfix

#73 [FU-302] 지난예약건 조회 API 필터링기능 보완
  src/main/java/com/foru/freebe/product/respository/ProductRepository.java
  src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerPastReservationService.java
Labels: 🛠️ bugfix, ✨api-update

#72 [FU-186] 카카오 알림톡 발송 기능 개발
  .github/workflows/cd_workflow_dev.yml
  src/main/java/com/foru/freebe/auth/controller/AuthController.java
  src/main/java/com/foru/freebe/auth/dto/LoginResponse.java
  src/main/java/com/foru/freebe/auth/dto/UnlinkRequest.java
  src/main/java/com/foru/freebe/auth/service/KakaoAuthService.java
  src/main/java/com/foru/freebe/auth/service/KakaoLoginService.java
  src/main/java/com/foru/freebe/auth/service/KakaoUnlinkService.java
  src/main/java/com/foru/freebe/config/WebClientConfig.java
  src/main/java/com/foru/freebe/errors/errorcode/ReservationErrorCode.java
  src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
  src/main/java/com/foru/freebe/message/dto/Button.java
  src/main/java/com/foru/freebe/message/dto/DataResponse.java
  src/main/java/com/foru/freebe/message/dto/MessageSendRequest.java
  src/main/java/com/foru/freebe/message/dto/MessageSendResponse.java
  src/main/java/com/foru/freebe/message/service/MessageSendService.java
  src/main/java/com/foru/freebe/notice/dto/NoticeDto.java
  src/main/java/com/foru/freebe/product/dto/photographer/ProductRegisterRequest.java
  src/main/java/com/foru/freebe/product/dto/photographer/UpdateProductDetailRequest.java
  src/main/java/com/foru/freebe/profile/dto/UpdateProfileRequest.java
  src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
  src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
  src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
  src/main/java/com/foru/freebe/reservation/dto/ReservationStatusUpdateRequest.java
  src/main/java/com/foru/freebe/reservation/dto/ShootingInfoRequest.java
  src/main/java/com/foru/freebe/reservation/dto/UpdatePhotographerMemoRequest.java
  src/main/java/com/foru/freebe/reservation/dto/alimtalk/CustomerCancelInfo.java
  src/main/java/com/foru/freebe/reservation/dto/alimtalk/StatusUpdateNotice.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/main/java/com/foru/freebe/reservation/service/ReservationService.java
  src/main/java/com/foru/freebe/reservation/service/ReservationVerifier.java
  src/main/resources/application.yaml
Labels: 🌟 feature, ✨api-update

#74 [FU-313] UI 변경에 따른 회원가입 API/비즈니스 로직 업데이트
  .github/workflows/cd_workflow_dev.yml
  .github/workflows/cd_workflow_prod.yml
  src/main/java/com/foru/freebe/auth/controller/AuthController.java
  src/main/java/com/foru/freebe/auth/model/ServiceTerms.java
  src/main/java/com/foru/freebe/auth/model/ServiceTermsAgreement.java
  src/main/java/com/foru/freebe/auth/service/KakaoAuthService.java
  src/main/java/com/foru/freebe/config/CorsConfig.java
  src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
  src/main/java/com/foru/freebe/member/entity/MemberTermAgreement.java
  src/main/java/com/foru/freebe/member/service/PhotographerJoinService.java
  src/main/java/com/foru/freebe/message/dto/MessageSendRequest.java
  src/main/java/com/foru/freebe/message/service/MessageSendService.java
Labels: ✨api-update

#78 [v1.1.1] 릴리즈
  src/main/java/com/foru/freebe/auth/model/ServiceTermsAgreement.java
Labels: 🛠️ bugfix, 🧸 release
