Repository SWM-15th-ForU/freebe-Backend, pull requests merged in 2024-09, with the labels that each got.

#27 [FU-196] 로그인 과정에서 발생하는 버그 픽스
  src/main/java/com/foru/freebe/config/CorsConfig.java
  src/main/java/com/foru/freebe/config/CustomAccessDeniedHandler.java
  src/main/java/com/foru/freebe/config/SecurityConfig.java
  src/main/java/com/foru/freebe/errors/handler/GlobalExceptionHandler.java
  src/main/java/com/foru/freebe/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/foru/freebe/member/entity/Member.java
Labels: 🛠️ Bug Fix

#23 [FU-181] 사진의뢰자 측에서 사진작가 프로필을 조회하는 API 구현
  src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
  src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
  src/main/java/com/foru/freebe/profile/dto/LinkInfo.java
  src/main/java/com/foru/freebe/profile/dto/ProfileResponse.java
  src/main/java/com/foru/freebe/profile/entity/Link.java
  src/main/java/com/foru/freebe/profile/entity/Profile.java
  src/main/java/com/foru/freebe/profile/repository/LinkRepository.java
  src/main/java/com/foru/freebe/profile/repository/ProfileRepository.java
  src/main/java/com/foru/freebe/profile/service/ProfileService.java
Labels: ✨Feature

#22 [FU-118] 사진의뢰자 측 신청서 조회 API 구현
  src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
  src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
  src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
  src/main/java/com/foru/freebe/reservation/dto/PhotoOption.java
  src/main/java/com/foru/freebe/reservation/dto/ReservationInfoResponse.java
  src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
Labels: ✨Feature

#26 [FU-126] 이미지 업로드 및 리사이즈 로직 구현
  build.gradle
  src/main/java/com/foru/freebe/common/service/S3ImageService.java
  src/main/java/com/foru/freebe/config/S3Config.java
  src/main/java/com/foru/freebe/errors/errorcode/AwsErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/ImageErrorCode.java
  src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
  src/main/java/com/foru/freebe/product/dto/photographer/ProductRegisterRequest.java
  src/main/java/com/foru/freebe/product/dto/photographer/RegisteredProductResponse.java
  src/main/java/com/foru/freebe/product/entity/ProductImage.java
  src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
  src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
  src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
  src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
  src/main/java/com/foru/freebe/reservation/dto/PhotoOption.java
  src/main/java/com/foru/freebe/reservation/dto/ReferenceImageUrls.java
  src/main/java/com/foru/freebe/reservation/entity/ReferenceImage.java
  src/main/java/com/foru/freebe/reservation/repository/ReferenceImageRepository.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
  src/main/resources/application.yaml
Labels: ✨Feature

#29 [FU-199] 신청서 리스트뷰 조회 API 보완
  src/main/java/com/foru/freebe/constants/SortConstants.java
  src/main/java/com/foru/freebe/reservation/dto/FormComponent.java
  src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
Labels: ✨api-update

#28 [FU-133] 로그아웃 로직 구현
  src/main/java/com/foru/freebe/config/CustomLogoutHandler.java
  src/main/java/com/foru/freebe/config/SecurityConfig.java
  src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
  src/main/java/com/foru/freebe/errors/errorcode/JwtErrorCode.java
  src/main/java/com/foru/freebe/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/foru/freebe/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/foru/freebe/jwt/model/JwtToken.java
  src/main/java/com/foru/freebe/jwt/repository/JwtTokenRepository.java
  src/main/java/com/foru/freebe/jwt/service/JwtProvider.java
  src/main/java/com/foru/freebe/jwt/service/JwtService.java
  src/main/java/com/foru/freebe/jwt/service/JwtVerifier.java
Labels: 🌟feature

#30 [FU-123] 신청서 상태변경 API
  src/main/java/com/foru/freebe/auth/controller/AuthController.java
  src/main/java/com/foru/freebe/auth/dto/LoginRequest.java
  src/main/java/com/foru/freebe/member/entity/Role.java
  src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
  src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
  src/main/java/com/foru/freebe/reservation/dto/ReservationStatusUpdateRequest.java
  src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
  src/main/java/com/foru/freebe/reservation/entity/ReservationHistory.java
  src/main/java/com/foru/freebe/reservation/entity/ReservationStatus.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
Labels: 🌟feature, ✨api-update

#33 [FU-179] 사진작가 회원가입 API 개발
  .github/workflows/cd_workflow_dev.yml
  src/main/java/com/foru/freebe/config/S3Config.java
  src/main/java/com/foru/freebe/member/controller/JoinController.java
  src/main/java/com/foru/freebe/member/service/MemberService.java
  src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
  src/main/java/com/foru/freebe/profile/entity/Profile.java
  src/main/java/com/foru/freebe/profile/entity/ProfileImage.java
  src/main/java/com/foru/freebe/profile/repository/ProfileImageRepository.java
  src/main/java/com/foru/freebe/profile/repository/ProfileRepository.java
  src/main/java/com/foru/freebe/profile/service/ProfileService.java
  src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/main/java/com/foru/freebe/s3/S3ImageService.java
  src/main/java/com/foru/freebe/s3/S3ImageType.java
  src/main/resources/application.yaml
Labels: 🌟feature

#36 [FU-228] CodeDeploy 배포 자동화 오류 분석 및 문제해결을 위한 스크립트 개선
  .github/workflows/cd_workflow_dev.yml
  scripts/start.sh
  scripts/stop.sh
Labels: ☄️ trouble-shooting

#40 [FU-217] 상품 관리 API 구현
  src/main/java/com/foru/freebe/errors/errorcode/ProductErrorCode.java
  src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
  src/main/java/com/foru/freebe/product/dto/photographer/ProductRegisterRequest.java
  src/main/java/com/foru/freebe/product/dto/photographer/UpdateProductDetailRequest.java
  src/main/java/com/foru/freebe/product/entity/Product.java
  src/main/java/com/foru/freebe/product/entity/ProductImage.java
  src/main/java/com/foru/freebe/product/respository/ProductComponentRepository.java
  src/main/java/com/foru/freebe/product/respository/ProductDiscountRepository.java
  src/main/java/com/foru/freebe/product/respository/ProductImageRepository.java
  src/main/java/com/foru/freebe/product/respository/ProductOptionRepository.java
  src/main/java/com/foru/freebe/product/respository/ProductRepository.java
  src/main/java/com/foru/freebe/product/service/CustomerProductService.java
  src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
  src/main/java/com/foru/freebe/product/service/ProductDetailConvertor.java
  src/main/java/com/foru/freebe/profile/entity/ProfileImage.java
  src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
  src/main/java/com/foru/freebe/s3/S3ImageService.java
  src/test/java/com/foru/freebe/product/service/PhotographerProductServiceTest.java
Labels: 🌟 feature

#45 [FU-264] S3관련 환경변수 수정
  .github/workflows/cd_workflow_dev.yml
  .github/workflows/ci_workflow_dev.yml
  src/main/java/com/foru/freebe/s3/S3ImageService.java
  src/main/resources/application.yaml
Labels: 🛠️ bugfix

#44 [FU-124] 신청서 상태변경 & 회원가입 API 테스트코드 작성
  .github/workflows/cd_workflow_dev.yml
  src/main/java/com/foru/freebe/auth/controller/AuthController.java
  src/main/java/com/foru/freebe/auth/service/KakaoAuthService.java
  src/main/java/com/foru/freebe/auth/service/KakaoLoginService.java
  src/main/java/com/foru/freebe/member/controller/JoinController.java
  src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
  src/main/java/com/foru/freebe/member/service/PhotographerJoinService.java
  src/main/java/com/foru/freebe/reservation/dto/ReservationStatusUpdateRequest.java
  src/test/java/com/foru/freebe/member/service/PhotographerJoinServiceTest.java
  src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java
  src/test/java/com/foru/freebe/reservation/service/ReservationServiceTest.java
Labels: ✅ test, 🫧 refactoring

#46 [FU-215] 지난예약 목록 조회 및 필터링+페이징 기능 구현
  src/main/java/com/foru/freebe/product/respository/ProductRepository.java
  src/main/java/com/foru/freebe/product/service/CustomerProductService.java
  src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
  src/main/java/com/foru/freebe/product/service/ProductDetailConvertor.java
  src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
  src/main/java/com/foru/freebe/reservation/dto/PastReservationFormComponent.java
  src/main/java/com/foru/freebe/reservation/dto/PastReservationResponse.java
  src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
  src/main/java/com/foru/freebe/reservation/service/PhotographerPastReservationService.java
Labels: 🌟 feature
